// import twoSum from '@/twoSum';
// import reverse from '@/reverse';
// import isPalindrome from '@/isPalindrome';
// // TODO // import romanToInt from '@/romanToInt';
// import longestCommonPrefix from '@/longestCommonPrefix';
// import isValid from '@/isValid';
// import mergeTwoLists from '@/mergeTwoLists';
// import removeDuplicates from '@/removeDuplicates';
// import removeElement from '@/removeElement';
// import strStr from '@/strStr';
// import searchInsert from '@/searchInsert';
// import maxSubArray from '@/maxSubArray';
// import lengthOfLastWord from '@/lengthOfLastWord';
// import plusOne from '@/plusOne';
// // TODO // import addBinary from '@/addBinary';
// // TODO // import mySqrt from '@/mySqrt';
// import climbStairs from '@/climbStairs';
// import deleteDuplicates from '@/deleteDuplicates';
// import merge from '@/merge';
// // no best
// import inorderTraversal from '@/inorderTraversal';
// import isSameTree from '@/isSameTree';
// import isSymmetric from '@/isSymmetric';
import maxDepth from '@/maxDepth';

console.log();

// twoSum();
// reverse();
// isPalindrome();
// // romanToInt();
// longestCommonPrefix();
// isValid();
// mergeTwoLists();
// removeDuplicates();
// removeElement();
// strStr();
// searchInsert();
// maxSubArray();
// lengthOfLastWord();
// plusOne();
// // addBinary();
// // mySqrt();
// climbStairs();
// deleteDuplicates();
// merge();
// inorderTraversal();
// isSameTree();
// isSymmetric();
maxDepth();

console.log();
